markdown: kramdown
remote_theme: benbalter/retlab

title: La lista de Regalos de Maria
description: Muchas gracias :)

lang: en-US

# Pages to include in header navigation
nav_pages:
  - index.html
  - mistallas.md
